# Generated by Django 5.2.7 on 2025-12-28 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hh_parser', '0002_city_company_platform_remove_vacancy_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='city',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='company',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='platform',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
