# Generated by Django 5.2.7 on 2026-01-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название блока')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('content', models.JSONField(default=dict, verbose_name='JSON контент')),
                ('block_type', models.CharField(choices=[('hero', 'Главный раздел'), ('stats', 'Статистика')], max_length=50, verbose_name='Тип блока')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Блок на главной странице',
                'verbose_name_plural': 'Блоки на главной странице',
                'ordering': ['order'],
            },
        ),
    ]
