# Generated by Django 5.2.7 on 2025-11-04 12:34


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superjob_parser', '0003_alter_superjob_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuperJob',
        ),
    ]
