# Generated by Django 5.2.7 on 2025-12-28 18:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='City name', max_length=50, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Company name', max_length=150, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HeadHunter', 'HeadHunter'), ('SuperJob', 'SuperJob'), ('Telegram', 'Telegram')], db_index=True, help_text='Name of the job search platform', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platforms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_vacancy_id', models.CharField(blank=True, db_index=True, help_text='Unique identifier from the source platform', max_length=25, null=True)),
                ('title', models.CharField(db_index=True, help_text='Job title', max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('url', models.URLField(blank=True, help_text='URL to the original vacancy posting', null=True, unique=True)),
                ('salary', models.CharField(blank=True, help_text='Salary information', max_length=120, null=True)),
                ('experience', models.CharField(blank=True, help_text='Required experience level', max_length=50, null=True)),
                ('employment', models.CharField(blank=True, help_text='Employment type (full-time, part-time, etc.)', max_length=40, null=True)),
                ('work_format', models.CharField(blank=True, help_text='Work format (remote, office, hybrid, etc.)', max_length=255, null=True)),
                ('schedule', models.CharField(blank=True, help_text='Work schedule', max_length=50, null=True)),
                ('address', models.CharField(blank=True, help_text='Physical address of the workplace', max_length=255, null=True)),
                ('skills', models.TextField(blank=True, help_text='Required skills and qualifications', null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed job description', null=True)),
                ('education', models.CharField(blank=True, help_text='Required education level', max_length=30, null=True)),
                ('contacts', models.CharField(blank=True, help_text='Contact information', max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the vacancy was added to the system')),
                ('published_at', models.DateTimeField(db_index=True, help_text='When the vacancy was published on the source platform')),
                ('city', models.ForeignKey(blank=True, help_text='City where the position is located', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='vacancies.city')),
                ('company', models.ForeignKey(blank=True, help_text='Company offering the position', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.company')),
                ('platform', models.ForeignKey(blank=True, help_text='Platform where the vacancy was posted', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.platform')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at', 'platform'], name='vacancies_v_publish_848807_idx'), models.Index(fields=['title', 'company'], name='vacancies_v_title_be0e00_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('platform__isnull', False), ('platform_vacancy_id__isnull', False)), fields=('platform_vacancy_id',), name='unique_platform_vacancy_id')],
            },
        ),
    ]
