# Generated by Django 5.2.7 on 2026-01-01 21:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['name'], 'verbose_name': 'Платформа', 'verbose_name_plural': 'Платформы'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-published_at'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, max_length=50, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, max_length=150, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(choices=[('HeadHunter', 'HeadHunter'), ('SuperJob', 'SuperJob'), ('Telegram', 'Telegram')], db_index=True, max_length=50, unique=True, verbose_name='Платформа'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='vacancies.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='contacts',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='education',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employment',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Занятость'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.platform', verbose_name='Платформа'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='platform_vacancy_id',
            field=models.CharField(blank=True, db_index=True, max_length=25, null=True, verbose_name='Идентификатор вакансии на платформе'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateTimeField(db_index=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='schedule',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(db_index=True, max_length=255, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Cсылка'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='work_format',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Формат работы'),
        ),
    ]
