# Generated by Django 5.2.7 on 2026-01-29 22:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_city_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vacancy',
            name='vacancies_v_publish_848807_idx',
        ),
        migrations.RemoveIndex(
            model_name='vacancy',
            name='vacancies_v_title_be0e00_idx',
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(choices=[('HeadHunter', 'HeadHunter'), ('SuperJob', 'SuperJob'), ('Telegram', 'Telegram')], max_length=50, unique=True, verbose_name='Платформа'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='vacancies.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='contacts',
            field=models.CharField(max_length=250, null=True, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='education',
            field=models.CharField(max_length=30, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employment',
            field=models.CharField(max_length=40, null=True, verbose_name='Занятость'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(max_length=50, null=True, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.platform', verbose_name='Платформа'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='platform_vacancy_id',
            field=models.CharField(max_length=25, verbose_name='Идентификатор вакансии на платформе'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateTimeField(verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(max_length=120, null=True, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='schedule',
            field=models.CharField(max_length=50, null=True, verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='skills',
            field=models.TextField(null=True, verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(db_index=True, max_length=255, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='url',
            field=models.URLField(null=True, unique=True, verbose_name='Cсылка'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='work_format',
            field=models.CharField(max_length=255, null=True, verbose_name='Формат работы'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['title', 'city'], name='vacancies_v_title_3c1b98_idx'),
        ),
    ]
