# Generated by Django 6.0.2 on 2026-04-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_remove_vacancy_vacancies_v_publish_848807_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='region',
            field=models.CharField(max_length=100, null=True, verbose_name='Регион'),
        ),
    ]
