# Generated by Django 5.2.7 on 2025-11-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foragencies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyplanfeature',
            name='description',
        ),
        migrations.RemoveField(
            model_name='companyinquiry',
            name='message',
        ),
        migrations.AddField(
            model_name='companyinquiry',
            name='company_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agencypricingplan',
            name='currency',
            field=models.CharField(default='₽', max_length=3),
        ),
        migrations.AlterField(
            model_name='agencypricingplan',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='agencypricingplan',
            name='period',
            field=models.CharField(default='мес', max_length=50),
        ),
        migrations.AlterField(
            model_name='agencypricingplan',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
