# Generated by Django 5.2.7 on 2025-11-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planfeature',
            name='description',
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='currency',
            field=models.CharField(default='₽', max_length=3),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='period',
            field=models.CharField(default='мес', max_length=50),
        ),
    ]
