# Generated by Django 5.2.7 on 2025-11-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_remove_planfeature_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
