# Generated by Django 5.2.7 on 2026-01-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_alter_pricingplan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='currency',
            field=models.CharField(default='RUB', max_length=3),
        ),
    ]
